### ISSUE TITLE
annoyances that I dunno how to solve

### ISSUE THREAD

**Issue by kronikpillow** [bakkeby/flexipatch-finalizer#1]
Ok, so one thing im annoyed by flexipatch-finalizer is

everytime I run flexipatch-finalizer it either completely deletes patches.h, or it changes all values to 0 after running it, this way, when I quickly want to experiment with some patch, I can't just change it, rerun it, and disable it later, every time I have to copy patches.def.h to patches.h and start over, and by the time I do it, I even forget sometimes what was the patch that I was testing

can we find a better solution for this?
patches.h shouldn't be deleted or overwritten by flexipatch-finalizer, it should stay as is after your modifications so that you can undo or add more to it, without having to commit anything

patches.def.h should be basically a selection of known working patches that you have as "defaults" for your build. or not sure exactly what the purpose of it is :dagger: 

another annoyance is the keep function, it keeps all patches but renames them with a _ which then makes us need to rename it back to file names without _ and to have to restart the process ...

eg we need a better solution on apply new patch / test the build / revert to the version that wasn't flexipatch finalized, and then add more patches or remove the recently applied patch

any suggestions?

or am I missing the point of the workflow? what would be a recommended workflow by you?

**Comment by bakkeby** [comment]
Hi @kronikpillow,

it sounds like you are making life a lot more complicated for yourself than it need to be.

> patches.def.h should be basically a selection of known working patches that you have as "defaults" for your build. or not sure exactly what the purpose of it is :dagger:

So something that I find often is that many people trying out suckless utilities don't quite understand the relation between `config.def.h` and `config.h`. What is the purpose of `config.def.h`?

It is the _default_ configuration that comes with dwm, st, etc. When you run `make` and a `config.h` does not exist, then the default configuration is copied to `config.h`. `config.h` is what is being used when dwm is compiled. It is, essentially, your personal configuration file where you add your own colour settings, and whatnot.

It's the same with `patches.def.h`. It just defines all the patch options that are available - and by default only the tile and monocle layouts are enabled (as with a bare dwm build). When you run `make` and a `patches.h` file does not exist, then the default configuration is copied to `patches.h`.

The purpose of `patches.h` is precisely that it's your personal patch choices, that's all.

> another annoyance is the keep function, it keeps all patches but renames them with a _ which then makes us need to rename it back to file names without _ and to have to restart the process ...

Yes this was basically just something I briefly used while testing the flexipatch-finalizer script. It's not particularly useful as-is.

> we need a better solution on apply new patch / test the build / revert to the version that wasn't flexipatch finalized, and then add more patches or remove the recently applied patch

You don't actually need the flexipatch-finalizer.

My workflow would be to just check out / clone dwm-flexipatch and run `make` to have `config.h` and `patches.h` created.

I'd then change enable, e.g., the ALPHA_PATCH by setting that to 1 in `patches.h` and run ```sudo make clean install```, exit and start dwm again.

If I'm not happy with the alpha patch then just change that option in `patches.h` to 0 again and recompile. If you are testing patches then this is the way to go.

Granted the `config.h` is massive and likely confusing this way, but in principle you shouldn't need to worry about configuration at this point except for checking key bindings for certain functionality. Alternatively you could just use a simple configuration file and copy in that what you need manually when trying out new patches. I personally just live with it as I maintain it and need to test all kinds of things.

If you are worried about breaking your current environment then starting dwm in a new virtual display manager like Xephyr is pretty cool, just make sure to use a different MOD key as otherwise it will just conflict with your current setup.

The flexipatch-finalizer is really only intended for when you have tried out all the patches you are interested in and have no further interest in messing with all the flexipatch bollocks. It just allows you to remove everything flexipatch related from your build including any unselected patches - it's your "final" build, with no further changes going in. I think of it as a cheap way to get a dwm with a set of patches without having to revert to patching manually.

If you do end up using the flexipatch-finalizer then the easiest thing here is to just copy the entire directory before running it in case you'd ever want to go back.

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
> @bakkeby 
It's the same with patches.def.h. It just defines all the patch options that are available - and by default only the tile and monocle layouts are enabled (as with a bare dwm build). When you run make and patches.h file does not exist, then the default configuration is copied to patches.h.
The purpose of patches.h is precisely that it's your personal patch choices, that's all.
> 

well, that's precisely my point mate when you run make it doesn't get created & if patches.h doesn't exist the flexipatch-finalizer doesn't run, while if you copy it your self and name it patches.h & run flexipatch-finalizer after creating patches.h, everything you have placed in patches.h gets reset to default, it doesn't keep the changes to patches.h after running flexipatch-finalizer either, as a matter of fact, it deletes it

**Comment by bakkeby** [comment]
Ah, I see the confusion. `patches.def.h` remains after you run flexipatch-finalizer, it shouldn't. The intention of the script is to remove all trace of flexipatch, including these files.

I'll add a few command line options to make this more practical.

**Comment by bakkeby** [comment]
Hi @kronikpillow,

I added a `-o` option to the script which allows you to specify an output / destination directory.

e.g.
```bash
flexipatch-finalizer.sh -r -d . -o ~/final/
````

If you'd explicitly want to not create a copy / output directory then you'd have to specify that the `-d` and the `-o` refers to the same directory.

Hope this helps.

Finalising a build like this shouldn't make any difference for the compiled binaries though. I'd still recommend just compiling dwm-flexipatch on it's own.

\
Thanks,

-Stein

**Comment by kronikpillow** [comment]
what do you mean by "I'd still recommend just compiling dwm-flexipatch on it's own." ?? you mean without running flexipatch-finalizer? that's a hell of a mess when writing configs :D

**Comment by kronikpillow** [comment]
Ahh, now I've read your full comments, ok, I get it now. Still, as I said some keybindings that I am used to are way off & conflicting with the default keybindings,
Changing every instance of the same key in the default config without running finalizer is very painful, especially considering that 80% of the patches, I will never even try out. Hence, the best solution for people testing patches without having to go through the full mess of all the #define things and #if statements is if we can have a workflow where we can: 
select patches
run flexipatch finalizer
make to create the first config.h
edit default keybindings
make install
test

then to be able to:
reset it back to the state before flexipatch finalizer, while keeping patches.h & modified config.h intact
add a new patch via patches.h
run flexipatch finalizer
vimdiff config.def.h with my config.h and add the generated differences from the config.def.h to my config.h.

or at least this is how I imagined the most natural workflow I can find

So now with the -o and -d option, I can achieve that?

**Comment by bakkeby** [comment]
> what do you mean by "I'd still recommend just compiling dwm-flexipatch on it's own." ?? you mean without running flexipatch-finalizer? that's a hell of a mess when writing configs :D

Yes, the config file may be confusing, but if you forget about your personal preferences for colours and keybindings, then you can try out a series of patches in quick succession to see if the way they behave (with the existing keybindings) is useful to you or not.

Once you have selected the 20 or so patches that you know you want, then you could run flexipatch-finalizer and start customising keybindings and whatnot to tailor them to your workflow.

> So now with the -o and -d option, I can achieve that?

Yes I'd think so. You'd have a ~/path/to/dwm-flexipatch/ right, then you'd run something like:
```bash
cd ~/path/to/dwm-flexipatch/
flexipatch-finalizer.sh -r -d . -o ~/final/
```
What happens is that the entirety of your dwm-flexipatch directory is copied to ~/final/, and flexipatch is applied on that (stripping everything flexipatch related). Then you can just repeat the process for any new changes you make.

**Comment by kronikpillow** [comment]
nice! off to testing :D !

**Comment by kronikpillow** [comment]
ok, so it does what is intended, although if output directory is in dmw-flexipatch/build then it says i cant flexipatch finalize it in the same directory, even thou output is set to a different dir in the same path. 

other thing is, if you flexpatch finalize it to a different directory out of the dwm-flexipatch dir, it does what is intended, but can't make cuz it lacks patches.def.h & patches.h

❯ make
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
CC       = cc
cp config.def.h config.h
cp patches.def.h patches.h
cp: cannot stat 'patches.def.h': No such file or directory
make: *** [Makefile:26: patches.h] Error 1


..

so the flexipatch finalize process either needs to copy patches.h & patches.def.h to output directory, or the process needs to remove the need for it from the make file

**Comment by bakkeby** [comment]
Ah, yes, makes sense. The script would have to also remove the lines from the Makefile.

**Comment by bakkeby** [comment]
I added a line to remove the unwanted entries in the Makefile, should allow you to compile now.

**Comment by kronikpillow** [comment]
```
[sudo] password for kronikpillow:
rm -f dwm drw.o dwm.o util.o dwm-6.2.tar.gz
dwm build options:
CFLAGS   = -std=c99 -pedantic -Wall -Wno-deprecated-declarations -Os -I/usr/X11R6/include -I/usr/include/freetype2 -D_DEFAULT_SOURCE -D_BSD_SOURCE -D_POSIX_C_SOURCE=2 -DVERSION="6.2" -DXINERAMA
LDFLAGS  = -L/usr/X11R6/lib -lX11 -lXinerama -lfontconfig -lXft -lXrender
CC       = cc
cp config.def.h config.h
cp patches.def.h patches.h
cp: cannot stat 'patches.def.h': No such file or directory
make: *** [Makefile:26: patches.h] Error 1
```
still the same problem....

**Comment by bakkeby** [comment]
Did you remember to update flexipatch-finalizer?

You should have this in there:
https://github.com/bakkeby/flexipatch-finalizer/commit/26d7c463b7a7874c23dca2c23074b076c26df759

**Comment by kronikpillow** [comment]
yeah forgot to update it :D :) all good now

**Comment by kronikpillow** [comment]
all good now :)

need more coffe
