### ISSUE TITLE
[Shebang tweak] - Generalize path to BASH

### ISSUE THREAD

**Issue by Atemo-C** [bakkeby/flexipatch-finalizer#14]
Greetings. Currently, the `flexipatch-finalizer.sh` script uses the following shebang: \
`#!/bin/bash`
However, some distributions have different paths to the `bash` shell, and this can lead to this script not running properly under these distributions by default.

A simple way to fix this issue is to use a shebang that uses common and generalized paths to binaries on all systems with `env`, specifically for `bash`; In our case, it would be the following:
`#!/usr/bin/env bash`

If this is something you think needs fixing, it would be nice to implement it. It is a general good habit to have with shell scripting in general.

**Comment by bakkeby** [comment]
Yes I don't mind changing this.

Also for shell scripts that are only ever run from the command line you don't even need the `/usr/bin/env`, you can just use a shebang like

```sh
#!bash
```

but I take it that it is not used that much because the script will likely not work if you run it some other way (for example via dmenu).

**Comment by Atemo-C** [comment]
> but I take it that it is not used that much because the script will likely not work if you run it some other way (for example via dmenu).

Indeed, and others as well. Thank you for this little tweak! Closing as completed.
